apiVersion: 1

deleteDatasources:
  - name: OCI LIP Prometheus
    orgId: 1

prune: true

datasources:
  - name: OCI LIP Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.12.0
      cacheLevel: High
      timeInterval: 5m
